### ISSUE TITLE
NameError: global name 'network_input' is not defined 

### ISSUE THREAD

**Issue by dhruvjain** [MarcBS/keras#11]
Hi, 
I was trying caffe to keras conversion module that you mentioned but im getting this error when i run the caffe2keras.py

global name 'network_input' is not defined

Any help?

This is the error I get:

```
python caffe2keras.py -load_path '/path/to.models' -prototxt 'train_val.prototxt' -caffemodel 'bvlc_reference_caffenet.caffemodel'
Using Theano backend.
Converting model...
CREATING MODEL
Traceback (most recent call last):
File "caffe2keras.py", line 45, in 
main(args)
File "caffe2keras.py", line 34, in main
model = convert.caffe_to_keras(args.load_path+'/'+args.prototxt, args.load_path+'/'+args.caffemodel, debug=args.debug)
File "/home/dhruv/Desktop/keras/keras/caffe/convert.py", line 42, in caffe_to_keras
debug)
File "/home/dhruv/Desktop/keras/keras/caffe/convert.py", line 138, in create_model
dim = get_data_dim(layers[network_input])
NameError: global name 'network_input' is not defined
```

I used it to convert caffenet model, the prototxt is this one:
name: "CaffeNet"

```
force_backward: true
input: "data"
input_dim: 1
input_dim: 3
input_dim: 227
input_dim: 227

input: "label"
input_dim: 1
input_dim: 1
input_dim: 1
input_dim: 1

layer {
name: "conv1"
type: "Convolution"
bottom: "data"
top: "conv1"
convolution_param {
num_output: 96
kernel_size: 11
stride: 4
}
}

layer {
name: "relu1"
type: "ReLU"
bottom: "conv1"
top: "conv1"
}
layer {
name: "pool1"
type: "Pooling"
bottom: "conv1"
top: "pool1"
pooling_param {
pool: MAX
kernel_size: 3
stride: 2
}
}
layer {
name: "norm1"
type: "LRN"
bottom: "pool1"
top: "norm1"
lrn_param {
local_size: 5
alpha: 0.0001
beta: 0.75
}
}
layer {
name: "conv2"
type: "Convolution"
bottom: "norm1"
top: "conv2"
convolution_param {
num_output: 256
pad: 2
kernel_size: 5
group: 2
}
}
layer {
name: "relu2"
type: "ReLU"
bottom: "conv2"
top: "conv2"
}
layer {
name: "pool2"
type: "Pooling"
bottom: "conv2"
top: "pool2"
pooling_param {
pool: MAX
kernel_size: 3
stride: 2
}
}
layer {
name: "norm2"
type: "LRN"
bottom: "pool2"
top: "norm2"
lrn_param {
local_size: 5
alpha: 0.0001
beta: 0.75
}
}
layer {
name: "conv3"
type: "Convolution"
bottom: "norm2"
top: "conv3"
convolution_param {
num_output: 384
pad: 1
kernel_size: 3
}
}
layer {
name: "relu3"
type: "ReLU"
bottom: "conv3"
top: "conv3"
}
layer {
name: "conv4"
type: "Convolution"
bottom: "conv3"
top: "conv4"
convolution_param {
num_output: 384
pad: 1
kernel_size: 3
group: 2
}
}
layer {
name: "relu4"
type: "ReLU"
bottom: "conv4"
top: "conv4"
}
layer {
name: "conv5"
type: "Convolution"
bottom: "conv4"
top: "conv5"
convolution_param {
num_output: 256
pad: 1
kernel_size: 3
group: 2
}
}
layer {
name: "relu5"
type: "ReLU"
bottom: "conv5"
top: "conv5"
}
layer {
name: "pool5"
type: "Pooling"
bottom: "conv5"
top: "pool5"
pooling_param {
pool: MAX
kernel_size: 3
stride: 2
}
}
layer {
name: "fc6"
type: "InnerProduct"
bottom: "pool5"
top: "fc6"
inner_product_param {
num_output: 4096
}
}
layer {
name: "relu6"
type: "ReLU"
bottom: "fc6"
top: "fc6"
}
layer {
name: "drop6"
type: "Dropout"
bottom: "fc6"
top: "fc6"
dropout_param {
dropout_ratio: 0.5
}
}
layer {
name: "fc7"
type: "InnerProduct"
bottom: "fc6"
top: "fc7"
inner_product_param {
num_output: 4096
}
}

layer {
name: "relu7"
type: "ReLU"
bottom: "fc7"
top: "fc7"
}

layer {
name: "drop7"
type: "Dropout"
bottom: "fc7"
top: "fc7"
dropout_param {
dropout_ratio: 0.5
}
}

layer {
name: "fc8"
type: "InnerProduct"
bottom: "fc7"
top: "fc8"
inner_product_param {
num_output: 1000
}
}
```

**Comment by dhruvjain** [comment]
python caffe2keras.py -load_path '/path/to.models' -prototxt 'train_val.prototxt' -caffemodel 'bvlc_reference_caffenet.caffemodel'
Using Theano backend.
Converting model...
CREATING MODEL
Traceback (most recent call last):
  File "caffe2keras.py", line 45, in <module>
    main(args)
  File "caffe2keras.py", line 34, in main
    model = convert.caffe_to_keras(args.load_path+'/'+args.prototxt, args.load_path+'/'+args.caffemodel, debug=args.debug)
  File "/home/dhruv/Desktop/keras/keras/caffe/convert.py", line 42, in caffe_to_keras
    debug)
  File "/home/dhruv/Desktop/keras/keras/caffe/convert.py", line 138, in create_model
    dim = get_data_dim(layers[network_input])
NameError: global name 'network_input' is not defined

**Comment by MarcBS** [comment]
@dhruvjain I have edited your message for the rest of the users to better understand your problem.

Looking at your prototxt I can see some problems:
- The first line "force_backward: true" should be removed.
- The following lines are not needed either:
  input: "label"
  input_dim: 1
  input_dim: 1
  input_dim: 1
  input_dim: 1
- You must include the following data layer before any other layer of the model:

```
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
}
```

**Comment by dhruvjain** [comment]
Actually I need to calculate gradient values using caffe and for the I added those extra lines in prototxt. So if I calculate gradient values using keras for caffenet I would not need those?

Thanks

**Comment by MarcBS** [comment]
You definitely don't need those values for converting the model to Keras. 

Aside from this, I suppose that you can calculate the gradients in some way with a Keras model, although you should probably investigate this functionality in the original Keras' documentation.

**Comment by dhruvjain** [comment]
I changed the .prototxt file but still I get the same error. I also tried feeding train_val.prototxt file of original caffenet model and the error remains

**Comment by MarcBS** [comment]
I used the train_val.prototxt [provided by caffe](https://github.com/BVLC/caffe/blob/master/models/bvlc_reference_caffenet/train_val.prototxt) just changing the header and worked like a charm.

Here is the header of the prototxt that I added:

```
name: "CaffeNet"
input: "data"
input_dim: 10
input_dim: 3
input_dim: 227
input_dim: 227
```

Tell me if this solves your problem.

**Comment by dhruvjain** [comment]
Cool, I did the same after adding the header and it worked. Thanks a lot :)
