### ISSUE TITLE
NameError: global name 'network_input' is not defined

### ISSUE THREAD

**Issue by AvenSun** [MarcBS/keras#14]
error occured when trying to convert VGG_TEXT model downloaded from[ here](http://nicolaou.homouniversalis.org/assets/vgg_text/)

> Converting model...
> CREATING MODEL
> Traceback (most recent call last):
>   File "caffe2keras.py", line 45, in <module>
>     main(args)
>   File "caffe2keras.py", line 34, in main
>     model = convert.caffe_to_keras(args.load_path+'/'+args.prototxt, args.load_p
> ath+'/'+args.caffemodel, debug=args.debug)
>   File "D:\Program Files\Python27\lib\site-packages\keras-1.0.5-py2.7.egg\keras\
> caffe\convert.py", line 43, in caffe_to_keras
>     debug)
>   File "D:\Program Files\Python27\lib\site-packages\keras-1.0.5-py2.7.egg\keras\
> caffe\convert.py", line 147, in create_model
>     dim = get_data_dim(layers[network_input])
> NameError: global name 'network_input' is not defined

**Comment by MarcBS** [comment]
Hi @Adesun, check this issue #11.

**Comment by AvenSun** [comment]
@MarcBS 
 Got it ! 
THX
