### ISSUE TITLE
Cannot make the conversion tool run

### ISSUE THREAD

**Issue by ruslanagit** [MarcBS/keras#16]
I am trying to convert the U-NET model from caffe to keras.
The model was downloaded from [U-NET webpage](http://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/) - here is the [direct link](http://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/u-net-release-2015-10-02.tar.gz) 

I was trying to run the following command
`python caffe2keras.py -load_path 'Downloads\u-net-release' -prototxt 'phseg_v5-train.prototxt' -caffemodel 'phseg_v5.caffemodel'
`
But ran into multiple issues. Some of the errors include - print errors, import errors, and type errors... (fixing one error just reveals another one...)
I guess my environment just does not support it.
I am running the latest keras with theano backend, on windows 10 and python 3.5
I don't have caffe installation.

Could anyone please help me? Are there any other ways to run the tool? Should I use a different tool in my environment?
Help would be highly appreciated! Thanks.

**Comment by MarcBS** [comment]
If you take a look at the main [README](https://github.com/MarcBS/keras/blob/master/README.md) file you will see that we only support Python 2.7, I can not guarantee that it will work on python 3.

Furthermore, you have to use this Keras fork for both converting and running the model, the converter will not work on the main Keras repo.

**Comment by ruslanagit** [comment]
All what I need is to convert one public caffe model. If the tool can only run in very particular (and outdated) environment, its useless. I am still trying to make it work, but kind of depressed...

I fixed the print errors (which I assume is the main problem with Python 3, right?), 
installed the missing  protobuf package with pip install command. 
uninstalled current keras version with pip uninstll, and finally 
installed your fork from root directory with python setup.py install.

Still, the tool cannot run, even on the example model downloaded from your branch.
I get the following error:

```
  File "caffe2keras.py", line 1, in <module>
    import keras.caffe.convert as convert
  File "C:\Program Files\Anaconda3\lib\site-packages\keras-1.0.5-py3.5.egg\keras\caffe\convert.py", line 9, in <module>
    from . import caffe_pb2 as caffe
  File "C:\Program Files\Anaconda3\lib\site-packages\keras-1.0.5-py3.5.egg\keras\caffe\caffe_pb2.py", line 799, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  File "C:\Program Files\Anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 872, in _ParseOptions
    message.ParseFromString(string)
  File "C:\Program Files\Anaconda3\lib\site-packages\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Program Files\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1088, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

```

I have no idea how to fix this. Any suggestions?

If there is no chance to make it work on my computer, could anyone with working environment convert the model please? I could make sure its compatible with the latest keras, and contribute into the master branch if there is demand for this.
