### ISSUE TITLE
Error converting caffe model

### ISSUE THREAD

**Issue by msollami** [MarcBS/keras#2]
I'm getting an exeception for unknown node/input identifier: data

```
$python keras/caffe/caffe2keras.py -load_path "/Users/mike/Research/models/bvlc_googlenet" -prototxt train_val.prototxt -caffemodel bvlc_googlenet.caffemodel
Using Theano backend.
Couldn't import dot_parser, loading of dot files will not be possible.
/Users/mike/.virtualenvs/caffe/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Converting model...
Traceback (most recent call last):
  File "keras/caffe/caffe2keras.py", line 45, in <module>
    main(args)
  File "keras/caffe/caffe2keras.py", line 34, in main
    model = convert.caffe_to_keras(args.load_path+'/'+args.prototxt, args.load_path+'/'+args.caffemodel, debug=args.debug)
  File "/Users/mike/Research/packages/caffe_to_keras/keras/caffe/convert.py", line 43, in caffe_to_keras
    debug)
  File "/Users/mike/Research/packages/caffe_to_keras/keras/caffe/convert.py", line 183, in create_model
    model.add_node(ZeroPadding2D(padding=(pad_h, pad_w)), name=name + '_zeropadding', input=input_layer_name)
  File "/Users/mike/Research/packages/caffe_to_keras/keras/layers/containers.py", line 357, in add_node
    raise Exception('Unknown node/input identifier: ' + input)
Exception: Unknown node/input identifier: data

```

**Comment by msollami** [comment]
@MarcBS Was wondering if you were able to take a took at this issue?

**Comment by MarcBS** [comment]
Sorry @msollami , I didn't receive any notification about this issue being published.

It looks like your .prototxt file includes the 'input' field in the header (e.g. input: "data"). For some reason the caffe models' reader does not allow that field to exists. You can solve the problem by just removing that line. 

The following example of a valid .prototxt file header is included in 'keras/caffe/models/train_val_for_keras.prototxt':

name: "GoogleNet"
input_dim: 10
input_dim: 3
input_dim: 224
input_dim: 224

**Comment by brettbj** [comment]
@MarcBS I'm actually having the same issue with the VGG-face model - but I've removed data from my header. Apologies if this is a simple fix, I'm not very familiar with caffe. (prototxt file attached) I'll play with the names to see if I can solve it on my own

Exception: Unknown node/input identifier: conv1_1

[VGG_FACE_deploy.prototxt.tar.gz](https://github.com/MarcBS/keras/files/191206/VGG_FACE_deploy.prototxt.tar.gz)

**Comment by MarcBS** [comment]
Hi @brettbj, I took a look at your .prototxt file. If you compare it to the example .prototxt that I included in keras/caffe/models/train_val_for_keras.prototxt it looks like the most probable cause of the error is that your model does not have the input layer.

You can probably solve it by adding this first layer to your file:

layer {
  name: "data"
  type: "Data"
  top: "data"
}

And changing the parameter 'top' of your first convolutional layer to 'data'.

**Comment by wangjiasi** [comment]
HI, I have a issue when I try to convert the alexnet model, here is the train_val.prototxt and the exeception
![convert](https://cloud.githubusercontent.com/assets/15626901/15799673/c2bf3b1c-2a96-11e6-82bc-31daf0f9020f.png)

[train_val.prototxt.zip](https://github.com/MarcBS/keras/files/298838/train_val.prototxt.zip)

and I get this kind of error when I am trying to fine-tuning the converted googlenet model.
![fine-tuning_error](https://cloud.githubusercontent.com/assets/15626901/15799679/d877410c-2a96-11e6-80a6-e464d90a2f7a.png)
here is my code 
[test_converted.py.zip](https://github.com/MarcBS/keras/files/298839/test_converted.py.zip)

@MarcBS Was wondering if you were able to take a took at this issue?

**Comment by JiasiWang** [comment]
@MarcBS Could you please take a look at this issue, thanks a lot

**Comment by MarcBS** [comment]
@wangjiasi The problem with your train_val.prototxt file is that you are declaring an input size of 224x224, but the correct one is 227x227.

About the test code, you must be aware that when using a Graph model in Keras you must provide a dict() in the following format (quoted from the code's comments):

> data: dictionary mapping input names and outputs names to
>                 appropriate numpy arrays. All arrays should contain
>                 the same number of samples.

Which means that you have to use as keys the very same input node names and output node names that are included in your model. I guess that in your test you are using GoogLeNet, which has three outputs 'loss1/loss1', 'loss2/loss2' and 'loss3/loss3'.
