### ISSUE TITLE
[Meta] Why is caffe2keras part of a keras fork?

### ISSUE THREAD

**Issue by jrao1** [MarcBS/keras#23]
Seems to me this tool doesn't need access to keras internals, so I'm not sure why it's part of a keras fork. I made some changes to the tool that could be useful, but I couldn't fork this repository since I already forked the original keras.

**Comment by lvapeab** [comment]
There was already a discussion [here](https://github.com/fchollet/keras/pull/1669) regarding whether caffe2keras  should be a fork or should it be included in the main Keras repo.
