### ISSUE TITLE
deconvolution used in this model is not currently supported

### ISSUE THREAD

**Issue by DianaYu0601** [MarcBS/keras#26]
hi, thank you for your share of this useful project! 

I notice that you have included DECONVOLUTION in your caffe_utils.py , but the convert is not yet supported. I wonder is their any chance you would like to update this part in the future?

thank you very much!

**Comment by MarcBS** [comment]
Thank you for your interest @DianaYu0601 

I'm afraid I am not planning to update the converter anytime soon. I am involved in several other projects and I can't spend my time on this.

Although, if you are interested in this feature, any improvement proposed through a pull request would be very welcome! :)

**Comment by akshaychawla** [comment]
Hey Marc!

I wanted to convert vgg16 based FCN models for segmentation so I forked your repo and added support for deconv and crop layers, shall I raise a PR for the same?

**Comment by MarcBS** [comment]
Hi @akshaychawla , that would be great! 

Submit a PR anytime you want. If you could provide me with an example of network for testing the conversion that would be perfect.

**Comment by akshaychawla** [comment]
Sure! I'll also include an alexnet-fcn model in the keras/keras/caffe/models/ folder, also I've only implemented the graph conversion, still working on the weights!

**Comment by MarcBS** [comment]
In that case let me know when you finish the weights part in order to test it.

**Comment by akshaychawla** [comment]
I just created a PR, now supports weight copying as well!
