### ISSUE TITLE
convert doesn't seem to generate correct weights

### ISSUE THREAD

**Issue by mathDR** [MarcBS/keras#3]
In keras/caffe/convert.py, the function convert_weights never seems to overwrite weights_p with the true value of the weight matrix (if typ == 'convolution').  weights_p is initialized to all zeros on line 337, but never overwritten with blobs[0].data as if the layer was 'inner_product' (line 303).

Dan

**Comment by sytrus-in-github** [comment]
@mathDR weight_p is overwirtten via group_weights on line 353~357.
