### ISSUE TITLE
Does this fork support convert caffemodel using 3D Convolution?

### ISSUE THREAD

**Issue by bityangke** [MarcBS/keras#30]
Does this fork support convert caffemodel using 3D Convolution?
More specific, https://github.com/facebook/C3D

**Comment by MarcBS** [comment]
No, it doesn't, although you could add it if you are interested.
[Here](https://github.com/MarcBS/keras/blob/master/keras/caffe/convert.py#L99) you can see all the layers supported right now.

**Comment by bityangke** [comment]
@MarcBS Thank you very much!
I noticed that it doesn't , and the caffe_pb2.py can not parse the convolution3d layer in C3D.
So I have to something tedious coding to get weights from blobs and reshape.
