### ISSUE TITLE
Use non-standard version of caffe for model conversion.

### ISSUE THREAD

**Issue by yash0307** [MarcBS/keras#41]
I used non-standard version of caffe for training my model. When I tried to convert it to keras model, this is the error I got : "caffe.LayerParameter" has no field named "transpose_param". Could you please tell me how can I use caffe2keras.py script specifying a different built of caffe.

**Comment by yash0307** [comment]
I've managed a workaround for previous error. However, I'm getting a ValueError now.

ValueError: Shape must be rank 4 but is rank 5 for 'caffe.SpatialConvolution_0_zeropadding/Pad' (op: 'Pad') with input shapes: [1,?,1,100,32], [4,2].

**Comment by MarcBS** [comment]
I am not sure about that last error, but if you what to use a different version of Caffe you should change the [caffe_pb2.py](https://github.com/MarcBS/keras/blob/master/keras/caffe/caffe_pb2.py) file. You should find it in the python directory in your version of Caffe.

**Comment by yash0307** [comment]
@MarcBS Thank you for the quick response.
