### ISSUE TITLE
Can you rebase this branch?

### ISSUE THREAD

**Issue by bhack** [MarcBS/keras#7]
Could really help if you could rebase this fork on new keras api in master.

**Comment by MarcBS** [comment]
@bhack I have just applied the rebase.

**Comment by bhack** [comment]
You have reopened, is it not complete?

**Comment by MarcBS** [comment]
Yes, it is not complete, sorry. I have rebased the code from the main repo, but now I realized that the Caffe2Keras converter is not working. Although the rest works fine.

In a few days when I have some time I will fix this.

**Comment by bhack** [comment]
@lenlen has an updated version of Caffe2Keras rebased on master at https://github.com/lenlen/keras/commits/caffe_importer

**Comment by lenlen** [comment]
My branch is a WIP with many prints for debug but it works with new keras api. In these days I'll clean the code.

**Comment by MarcBS** [comment]
Nice! @lenlen do you mind if I copy your code for conversion to my repo and put a link to your profile as an acknowledgement?

In case that you agree, would you mind leaving a comment here whenever you finish working on your code? Thanks!

**Comment by lenlen** [comment]
Yes, I agree

**Comment by MarcBS** [comment]
@bhack now the fork is rebased and working 100%
@lenlen I used your code in the converter and added your name in the [README](https://github.com/MarcBS/keras/blob/master/keras/caffe/README.md). So now we can convert Caffe models to Keras' FunctionalAPI models.

Thanks to both of you for your collaboration!
